### ISSUE TITLE
Питання

### ISSUE THREAD

**Issue by kluf** [DyplomProjectKafedraIFNTUNG/Dyplom_all_share#4]
Залив картинку question_1. Враховуючи те що дані про викладача беруться з 3-ох таблиць teacher, teacher_key, teacher_key_value і йому відповідають персональні навантаження з таблиці персональне навантаження з таблиць personal_navant, personal_navant_key, personal_navant_key_value дані дублюються це видно в колонці val. Я хотів би зробити так щоб замість усіх рядків був один рядок де були б усі ці дані. Як таке робити? Чи це треба робити вже в php? Процедура називається getTeacherLoadById

**Comment by BrunIF** [comment]
Я б збирав інформацію так:

``` sql
SELECT `tid` , `tkid` , `teacher_key`.`key_name` , `val`
FROM `teacher_key_value` , `teacher_key`
WHERE (
`tid` =1
)
AND (
`teacher_key`.`id` = `tkid`
)
```

Аналогічно витягуємо все, де буде назва поля та його значення.

p.s. Щоб питання адресувати конкретно мені - потрібно зробити асайн на мене. ;)

**Comment by BrunIF** [comment]
І звичайно треба вказати сортувати по "вазі" ключа. Бо інакше який з нього толк.
