### ISSUE TITLE
варіант реалізації опису предметів

### ISSUE THREAD

**Issue by yatsyshyn** [DyplomProjectKafedraIFNTUNG/Dyplom_all_share#5]
http://kn.kture.kharkov.ua/entrant_plans.php?type=courses&speciality=%CF%B2& 

по цій ссилці є варіант реалізації посеместровомого огляду предметів, це можна використати у 1-шому розділі, можливо з відси ви і більше зреалізуєте

**Comment by BrunIF** [comment]
Тоді для такого подібно зробити представлення view або ж процедуру.

p.s. Коли Петро вже підключиться?

**Comment by kluf** [comment]
Петро вже підключився. Щось вже робить. Я вже зробив так, як було в екселі http://i47.fastpic.ru/big/2013/0521/86/a87319d5048fc0fcb64ba60f085b8986.png - вибір кафедри, вибір груп(заочних чи стаціонарних), вибір дати початку та кінця семестру(весняний чи осінній) - і видає таке http://i47.fastpic.ru/big/2013/0521/76/8d88288d888d49d2e7c34b62f5bb9276.png
